### ISSUE TITLE
bug in preprocess.py

### ISSUE THREAD

**Issue by yoctta** [SCLBD/DeepfakeBench#10]
Traceback (most recent call last):
  File "/ssd/zhaohanqing/SOTA_deepfake_detection/DeepfakeBench/preprocessing/preprocess.py", line 518, in <module>
    preprocess(sub_dataset_path, None, mode, num_frames, stride)
  File "/ssd/zhaohanqing/SOTA_deepfake_detection/DeepfakeBench/preprocessing/preprocess.py", line 406, in preprocess
    face_predictor,
NameError: name 'face_predictor' is not defined

**Comment by YZY-stack** [comment]
Hi, 

I have updated the modified code of `preprocess.py`. Please go ahead and check the modified code, and I'll take a look at it to check for any remaining bugs. If you find any remaining issues, kindly let me know, and I will work on fixing them promptly. 
 
 I apologize for any inconvenience caused during this process.
