### ISSUE TITLE
I'm encountering some trouble in the implementation of the face x-ray model in the code.

### ISSUE THREAD

**Issue by fanfan1998** [SCLBD/DeepfakeBench#21]
Even when the training and test sets are exactly the same, the detector fails to achieve the desired results. In fact, the model is not trained at all. This is shown in the figure below:
![691bab1634e52a1d1c7d984cdecfc7f](https://github.com/SCLBD/DeepfakeBench/assets/44823699/6b44364c-ee12-4b95-a457-6d831df9dce7)
![2569356d3eefc0359c905ec786fa2b1](https://github.com/SCLBD/DeepfakeBench/assets/44823699/8b8b5862-fe9f-401a-942f-05ae042b6856)
Here's my settings on face x-ray, not sure if it's just me:
![4144479cc7b0c23ce5d9404eec39e49](https://github.com/SCLBD/DeepfakeBench/assets/44823699/37c67a09-ddc0-4cbb-bcb8-6f3b81bd43cf)
![5b3d68e909b602dc186dfdd586b4837](https://github.com/SCLBD/DeepfakeBench/assets/44823699/2dc385f5-a2eb-47a7-b8b9-a77dbd650110)
![9e16de65c169871f6e92dd8915221f9](https://github.com/SCLBD/DeepfakeBench/assets/44823699/1486df1d-c362-466b-b496-f46705fab3a4)

**Comment by fanfan1998** [comment]
Also, the naming of the .pkl file in generate_xray_nearest.py is a bit confusing, can you give a clearer version of this, thanks!

**Comment by YZY-stack** [comment]
Have you used the pre-trained weights of Face X-ray? If needed, I will update the processed file of this landmark dict, which saves the info for each image.

**Comment by gbljdgb** [comment]
@fanfan1998 Hello, I am also experiencing the same problem and was wondering if you have resolved the issue?
<img width="702" alt="image" src="https://github.com/SCLBD/DeepfakeBench/assets/88969496/e955e975-f36a-4b37-95c1-d9c516a9cbaf">

**Comment by J-T-kullo** [comment]
I meet the question as follows, could someone help me, thanks!

![image](https://github.com/user-attachments/assets/c805cf4c-8899-400b-b610-119f03ba3c80)

**Comment by J-T-kullo** [comment]
when I use the .pkl offered，I meet the new question，please！

Load HRnet
2024-08-22 08:57:24,265 - INFO - ===> Epoch[0] start!
2024-08-22 08:57:24,482 - INFO - data_dict saved to ./logs/training/facexray_None_2024-08-22-08-57-14/train/FF-NT/data_dict_train.pickle
  0%|                                                                                                                              | 0/9950 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "training/train.py", line 324, in <module>
    main()
  File "training/train.py", line 306, in main
    test_data_loaders=test_data_loaders,
  File "/root/data1/DeepfakeBench-main/training/trainer/trainer.py", line 239, in train_epoch
    for iteration, data_dict in tqdm(enumerate(train_data_loader),total=len(train_data_loader)):
  File "/root/miniconda3/envs/DeepfakeBench/lib/python3.7/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/root/miniconda3/envs/DeepfakeBench/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/DeepfakeBench/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/DeepfakeBench/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/DeepfakeBench/lib/python3.7/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/DeepfakeBench/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/DeepfakeBench/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/DeepfakeBench/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/data1/DeepfakeBench-main/training/dataset/ff_blend.py", line 486, in __getitem__
    manipulate_img, boundary, imid_bg = self.process_images(imid_fg, imid_bg, index)
  File "/root/data1/DeepfakeBench-main/training/dataset/ff_blend.py", line 393, in process_images
    fg_im, fg_shape, bg_im, bg_shape = self.preprocess_images(imid_fg, imid_bg)
  File "/root/data1/DeepfakeBench-main/training/dataset/ff_blend.py", line 256, in preprocess_images
    fg_im = self.load_rgb(imid_fg.replace('landmarks', 'frames').replace('npy', 'png'))
  File "/root/data1/DeepfakeBench-main/training/dataset/ff_blend.py", line 176, in load_rgb
    image_buf = np.frombuffer(image_bin, dtype=np.uint8)
TypeError: a bytes-like object is required, not 'NoneType'

**Comment by fsijphfsfhuiawe** [comment]
> when I use the .pkl offered，I meet the new question，please！
> 
> Load HRnet 2024-08-22 08:57:24,265 - INFO - ===> Epoch[0] start! 2024-08-22 08:57:24,482 - INFO - data_dict saved to ./logs/training/facexray_None_2024-08-22-08-57-14/train/FF-NT/data_dict_train.pickle 0%| | 0/9950 [00:00<?, ?it/s] Traceback (most recent call last): File "training/train.py", line 324, in main() File "training/train.py", line 306, in main test_data_loaders=test_data_loaders, File "/root/data1/DeepfakeBench-main/training/trainer/trainer.py", line 239, in train_epoch for iteration, data_dict in tqdm(enumerate(train_data_loader),total=len(train_data_loader)): File "/root/miniconda3/envs/DeepfakeBench/lib/python3.7/site-packages/tqdm/std.py", line 1178, in **iter** for obj in iterable: File "/root/miniconda3/envs/DeepfakeBench/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 652, in **next** data = self._next_data() File "/root/miniconda3/envs/DeepfakeBench/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data return self._process_data(data) File "/root/miniconda3/envs/DeepfakeBench/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data data.reraise() File "/root/miniconda3/envs/DeepfakeBench/lib/python3.7/site-packages/torch/_utils.py", line 461, in reraise raise exception TypeError: Caught TypeError in DataLoader worker process 0. Original Traceback (most recent call last): File "/root/miniconda3/envs/DeepfakeBench/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop data = fetcher.fetch(index) File "/root/miniconda3/envs/DeepfakeBench/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/miniconda3/envs/DeepfakeBench/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/data1/DeepfakeBench-main/training/dataset/ff_blend.py", line 486, in **getitem** manipulate_img, boundary, imid_bg = self.process_images(imid_fg, imid_bg, index) File "/root/data1/DeepfakeBench-main/training/dataset/ff_blend.py", line 393, in process_images fg_im, fg_shape, bg_im, bg_shape = self.preprocess_images(imid_fg, imid_bg) File "/root/data1/DeepfakeBench-main/training/dataset/ff_blend.py", line 256, in preprocess_images fg_im = self.load_rgb(imid_fg.replace('landmarks', 'frames').replace('npy', 'png')) File "/root/data1/DeepfakeBench-main/training/dataset/ff_blend.py", line 176, in load_rgb image_buf = np.frombuffer(image_bin, dtype=np.uint8) TypeError: a bytes-like object is required, not 'NoneType'

I met the same issue, have you solved this problem?
