### ISSUE TITLE
Code problem：ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by zhangruju** [SCLBD/DeepfakeBench#24]
Hello, when I use the same dataset for both training and testing, I encounter a ZeroDivisionError. However, when I use different datasets, I encounter dimension issues. Why is this happening? How can I resolve it? Could it be a problem with the code?

detector_path: .\training\config\detector\xception.yaml
train_dataset: [Celeb-DF-v2]
test_dataset: [Celeb-DF-v1]
Traceback (most recent call last):
  File "train.py", line 234, in <module>
    main()
  File "train.py", line 199, in main
    test_data_loaders = prepare_testing_data(config)
  File "train.py", line 106, in prepare_testing_data
    test_data_loaders[one_test_name] = get_test_data_loader(config, one_test_name)
  File "train.py", line 92, in get_test_data_loader
    mode='test',
  File "H:\DeepfakeBench-main\training\dataset\abstract_dataset.py", line 68, in __init__
    image_list, label_list = self.collect_img_and_label(dataset_list)
  File "H:\DeepfakeBench-main\training\dataset\abstract_dataset.py", line 193, in collect_img_and_label
    label_list, frame_path_list = zip(*shuffled)
ValueError: not enough values to unpack (expected 2, got 0)

train_dataset: [Celeb-DF-v2]
test_dataset: [Celeb-DF-v2]
Traceback (most recent call last):
  File "H:\DeepfakeBench-main\training\train.py", line 234, in <module>
    main()
  File "H:\DeepfakeBench-main\training\train.py", line 219, in main
    best_metric = trainer.train_epoch(
  File "H:\DeepfakeBench-main\training\trainer\trainer.py", line 238, in train_epoch
    if (step_cnt+1) % test_step == 0:
ZeroDivisionError: integer division or modulo by zero

**Comment by zhangruju** [comment]
I encountered similar errors even after changing the environment. How can I resolve this?

**Comment by YZY-stack** [comment]
I am sorry. I create a new environment and rerun the latest code using your settings. But I can still run the code without any modification. I cannot understand why are you getting this error. Can you send me an email to communicate more conveniently? ([yanzhiyuan1114@gmail.com](mailto:yanzhiyuan1114@gmail.com))
