### ISSUE TITLE
用ucf训练到第三轮出现问题

### ISSUE THREAD

**Issue by Usriscedjdj** [SCLBD/DeepfakeBench#49]
![image](https://github.com/SCLBD/DeepfakeBench/assets/96629668/896d309e-f8a6-4aec-9831-2d1e347c479a)
老哥们有无好的解决办法？

**Comment by githuboflk** [comment]
UCF使用pair_dataset，但是作者似乎没有提供pair的json文件。你是怎么训练起来的？

**Comment by BigWhiteBearZWJ** [comment]
请问你解决了吗

**Comment by IIyaJ** [comment]
Encountering a similar issue, the UCF model encountered an error during training：
Traceback (most recent call last):
  File "training/train.py", line 323, in <module>
    main()
  File "training/train.py", line 305, in main
    test_data_loaders=test_data_loaders,
  File "DeepfakeBench/training/trainer/trainer.py", line 313, in train_epoch
    step_cnt,
  File "DeepfakeBench/training/trainer/trainer.py", line 434, in test_epoch
    losses_one_dataset_recorder, predictions_nps, label_nps, feature_nps = self.test_one_dataset(test_data_loaders[key])
  File "DeepfakeBench/training/trainer/trainer.py", line 358, in test_one_dataset
    prediction_lists += list(predictions['prob'].cpu().detach().numpy())
KeyError: 'prob'

**Comment by IIyaJ** [comment]
Thank you for your reply. This problem has been solved. If you can
communicate with me, please contact ***@***.***

AlbertWYP ***@***.***> 于2025年2月18日周二 21:55写道：

**Comment by BA-dp** [comment]
> ![image](https://github.com/SCLBD/DeepfakeBench/assets/96629668/896d309e-f8a6-4aec-9831-2d1e347c479a) 老哥们有无好的解决办法？

你好，目前我跑出来的训练集损失下降正常，但测试集的损失震荡变大，请问你的测试集loss能正常下降吗？
