### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by CHEN-JINRUI1020** [SCLBD/DeepfakeBench#57]
Traceback (most recent call last):
  File "training/train.py", line 237, in <module>
    main()
  File "training/train.py", line 225, in main
    test_data_loaders=test_data_loaders,
  File "/data2/cjr/DeepfakeBench-main/training/trainer/trainer.py", line 184, in train_epoch
    losses = self.model.get_losses(data_dict, predictions)
  File "/data2/cjr/DeepfakeBench-main/training/detectors/ucf_detector.py", line 148, in get_losses
    return self.get_train_losses(data_dict, pred_dict)
  File "/data2/cjr/DeepfakeBench-main/training/detectors/ucf_detector.py", line 173, in get_train_losses
    loss_spe = self.loss_func['spe'](pred_spe, label_spe)
  File "/home/nuist/anaconda3/envs/DeepfakeBench/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data2/cjr/DeepfakeBench-main/training/loss/cross_entropy_loss.py", line 24, in forward
    loss = self.loss_fn(inputs, targets)
  File "/home/nuist/anaconda3/envs/DeepfakeBench/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nuist/anaconda3/envs/DeepfakeBench/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 1166, in forward
    label_smoothing=self.label_smoothing)
  File "/home/nuist/anaconda3/envs/DeepfakeBench/lib/python3.7/site-packages/torch/nn/functional.py", line 3014, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: CUDA error: device-side assert triggered

How do I solve this problem?

**Comment by MetroTY** [comment]
Hello, have you solved it yet? I had the same problem.

**Comment by MetroTY** [comment]
Don't use FF++ for the training set in the yaml.
