### ISSUE TITLE
i am getting key error while running the test command on test.py. can you help me to get this fixed

### ISSUE THREAD

**Issue by adityakeshri9234** [SCLBD/DeepfakeBench#75]
['in_channels', 'out_channels', 'kernel_size', 'stride', 'padding', 'dilation', 'groups', 'bias', 'padding_mode', 'device', 'dtype']
spatial_count=0 keep_stride_count=0
Traceback (most recent call last):
  File "training/test.py", line 198, in <module>
    main()
  File "training/test.py", line 176, in main
    test_data_loaders = prepare_testing_data(config)
  File "training/test.py", line 82, in prepare_testing_data
    test_data_loaders[one_test_name] = get_test_data_loader(config, one_test_name)
  File "training/test.py", line 67, in get_test_data_loader
    mode='test', 
  File "/content/DeepfakeBench/training/dataset/abstract_dataset.py", line 94, in __init__
    image_list, label_list, name_list = self.collect_img_and_label_for_one_dataset(one_data)
  File "/content/DeepfakeBench/training/dataset/abstract_dataset.py", line 156, in collect_img_and_label_for_one_dataset
    if not os.path.exists(self.config['dataset_json_folder']):
KeyError: 'dataset_json_folder'

**Comment by HUiTUi** [comment]
Loaded pretrained model (ImageNet)....
Traceback (most recent call last):
  File "/sharefiles/DeepfakeBench-main/training/train.py", line 319, in <module>
    main()
  File "/sharefiles/DeepfakeBench-main/training/train.py", line 287, in main
    scheduler = choose_scheduler(config, optimizer)
  File "/sharefiles/DeepfakeBench-main/training/train.py", line 217, in choose_scheduler
    raise NotImplementedError('Scheduler {} is not implemented'.format(config['lr_scheduler']))
NotImplementedError: Scheduler None is not implemented

too bug in your framework, that's awful!

**Comment by 010108** [comment]
I'm also experiencing this problem, can you please solve it

**Comment by YZY-stack** [comment]
Hi. Please see #81. I have solved this issue. Please see the lastest version for details!
