### ISSUE TITLE
KeyError: 'dataset_json_folder'

### ISSUE THREAD

**Issue by J-T-kullo** [SCLBD/DeepfakeBench#97]
Traceback (most recent call last):
  File "training/test.py", line 194, in <module>
    main()
  File "training/test.py", line 172, in main
    test_data_loaders = prepare_testing_data(config)
  File "training/test.py", line 81, in prepare_testing_data
    test_data_loaders[one_test_name] = get_test_data_loader(config, one_test_name)
  File "training/test.py", line 66, in get_test_data_loader
    mode='test', 
  File "/root/data1/DeepfakeBench-main/training/dataset/abstract_dataset.py", line 94, in __init__
    image_list, label_list, name_list = self.collect_img_and_label_for_one_dataset(one_data)
  File "/root/data1/DeepfakeBench-main/training/dataset/abstract_dataset.py", line 162, in collect_img_and_label_for_one_dataset
    if not os.path.exists(self.config['dataset_json_folder']):
KeyError: 'dataset_json_folder'

**Comment by J-T-kullo** [comment]
When i run the code:
python3 training/test.py --detector_path ./training/config/detector/xception.yaml --test_dataset "Celeb-DF-v1" "Celeb-DF-v2" "DFDCP" --weights_path ./training/weightsception_best.pth
I get the  error.

**Comment by J-T-kullo** [comment]
def main():
    # parse options and load config
    with open(args.detector_path, 'r') as f:
        config = yaml.safe_load(f)
    with open('./training/config/test_config.yaml', 'r') as f:
        config2 = yaml.safe_load(f)
    config.update(config2)     # <=======add this code line 
    if 'label_dict' in config:
        config2['label_dict']=config['label_dict']
    weights_path = None
    # If arguments are provided, they will overwrite the yaml settings
    if args.test_dataset:
        config['test_dataset'] = args.test_dataset
    if args.weights_path:
        config['weights_path'] = args.weights_path
        weights_path = args.weights_path
